### ISSUE TITLE
Windows 11 exception when calling GetDesktops()

### ISSUE THREAD

**Issue by renil-joy** [MScholtes/VirtualDesktop#44]
Hi 
Getting below exception in Windows 11 application, works fine in Windows 10. Using nuget package in a WPF application.
System.Collections.Generic.KeyNotFoundException: The given key 'IApplicationView' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at WindowsDesktop.Interop.ComInterfaceAssemblyBuilder.CreateAssembly()
   at WindowsDesktop.Interop.ComInterfaceAssemblyBuilder.GetAssembly()
   at WindowsDesktop.VirtualDesktop.InitializeCore()
   at WindowsDesktop.VirtualDesktop.InitializeIfNeeded()
   at WindowsDesktop.VirtualDesktop.GetDesktops()

Any help will be much appreciated

**Comment by aus10code** [comment]
If you're Windows 11 build _(System > About > Windows specifications to find out)_ is above **22489** you should be using the [Insider](https://github.com/MScholtes/VirtualDesktop/blob/master/VirtualDesktop11Insider.cs) file

`GetAllCurrentDesktops();` was added to `IVirtualDesktopManagerInternal` just before `GetDesktops(IntPtr hWndOrMon, out IObjectArray desktops);` on line 170

**Comment by renil-joy** [comment]
Thanks @aus10code. My bad, I was using [this nuget](https://github.com/Grabacr07/VirtualDesktop), mistook this repo as name looked same. Found a fix in that repo.
