### ISSUE TITLE
Error when create new desktop Windows Insider 25290

### ISSUE THREAD

**Issue by xquangdang** [MScholtes/VirtualDesktop#52]
I'm using Windows Insider build 25290. When create new Desktop I encounter this error: 
```
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at VirtualDesktop.IVirtualDesktopManagerInternal.CreateDesktop(IntPtr hWndOrMon)
   at VirtualDesktop.Desktop.Create()
   at VDeskTool.Program.Main(String[] args)
```

**Comment by MScholtes** [comment]
Hello @xquangdang,

this is not good news.

Greetings

Markus
