### ISSUE TITLE
Windows 11 23H2 build 22631.2861 not working (v1.19)

### ISSUE THREAD

**Issue by MorpheusUK** [MScholtes/VirtualDesktop#92]
I have installed the latest version at time of writing (v1.19 and also tried the Powershell version v1.5.9) which is failing with errors on Windows 11 23H2 build 22631.2861.
In the case of the C# VirtualDesktop11.exe and VirtualDesktop11-24H2.exe (tried in case the Guids now matched) I am getting the following errors:

PS C:\> .\VirtualDesktop11.exe -switch:1

Unhandled Exception: System.TypeInitializationException: The type initializer for 'VirtualDesktop.DesktopManager' threw an exception. ---> System.InvalidCastException: Specified cast is not valid.
   at VirtualDesktop.IServiceProvider10.QueryService(Guid& service, Guid& riid)
   at VirtualDesktop.DesktopManager..cctor()
   --- End of inner exception stack trace ---
   at VDeskTool.Program.Main(String[] args)

PS C:\> .\VirtualDesktop11-24H2.exe -switch:1

Unhandled Exception: System.TypeInitializationException: The type initializer for 'VirtualDesktop.DesktopManager' threw an exception. ---> System.InvalidCastException: Specified cast is not valid.
   at VirtualDesktop.IServiceProvider10.QueryService(Guid& service, Guid& riid)
   at VirtualDesktop.DesktopManager..cctor()
   --- End of inner exception stack trace ---
   at VDeskTool.Program.Main(String[] args)

**Comment by MScholtes** [comment]
Hello @MorpheusUK,

with version **22631.3085** _Microsoft_ changed the _Windows 11 API_ to access virtual desktops. Please update your _Windows_ to an supported version.

Greetings

Markus

**Comment by MorpheusUK** [comment]
Thanks for your reply, unfortunately this is actually my newly issued work laptop with upgrades managed by our IT department this I am unable to change the build installed.

**Comment by MScholtes** [comment]
Hello @MorpheusUK,

tell your management to fire the IT department: patching is mandatory!

Yes, version 1.16 should work, but might have other flaws.

Greetings

Markus

**Comment by CainKilled** [comment]
anIt looks like you're encountering issues with the VirtualDesktop11.exe and VirtualDesktop11-24H2.exe tools on Windows 11 23H2 build 22631.2861. The errors you're seeing are related to a System.TypeInitializationException caused by an InvalidCastException. This typically indicates that there is a mismatch or issue with the COM interfaces or GUIDs being used. try updating your wiondows environment there may be patches available for your virtual desktop. or use an older version of Virtual Desktop as a temp fix. One that was known to work well maybe version 1.16 of the VD Tool. just keep in mind there may be other problems when using the older version. good luck! Happy hunting!!

**Comment by MScholtes** [comment]
No issue, just need to patch Windows.
